Create a list of Luxury Hotels.

WITH LUXURY_HOTELS AS
(SELECT HOTEL, PRICE_RUPEES, NUMBER_OF_REVIEWS FROM DBO.HOTELS WHERE PRICE_RUPEES >= 15000)
SELECT *
FROM LUXURY_HOTELS;

Create a list of Popular Hotels.

WITH POPULAR_HOTELS AS
(SELECT HOTEL, PRICE_RUPEES, NUMBER_OF_REVIEWS FROM DBO.HOTELS WHERE NUMBER_OF_REVIEWS >= 2000)
SELECT *
FROM POPULAR_HOTELS;

Find hotels priced above the overall average.
--- CTE + CROSS JOIN

WITH AVG_PRICE AS
(SELECT AVG(PRICE_RUPEES) AS AVG_HOTEL_PRICE FROM DBO.HOTELS)
SELECT H.HOTEL,H.PRICE_RUPEES
FROM DBO.HOTELS H
CROSS JOIN AVG_PRICE A
WHERE H.PRICE_RUPEES > A.AVG_HOTEL_PRICE;

Create a list of History and Culture attractions.
-- CTE + JOIN

WITH CULTURAL_ATTRACTIONS AS
(SELECT P.POIs, T.PRIORITY_1 FROM DBO.PLACES P
  INNER JOIN DBO.TYPES T ON P.PID = T.PID
)
SELECT *
FROM CULTURAL_ATTRACTIONS
WHERE PRIORITY_1 = 'History and Culture';

Find Luxury Hotels that are also Highly Popular.

WITH LUXURY_HOTELS AS
(SELECT HOTEL, PRICE_RUPEES, NUMBER_OF_REVIEWS FROM DBO.HOTELS WHERE PRICE_RUPEES >= 15000)
SELECT *
FROM LUXURY_HOTELS;

Find Luxury Hotels that are also Highly Popular.

WITH LUXURY_HOTELS AS
(SELECT HOTEL, PRICE_RUPEES, NUMBER_OF_REVIEWS FROM DBO.HOTELS WHERE PRICE_RUPEES >= 15000)
SELECT *
FROM LUXURY_HOTELS
WHERE NUMBER_OF_REVIEWS >= 2000;

Find hotels from the Luxury Hotels CTE that have above-average reviews.
--- CTE + SubQuery

WITH LUXURY_HOTELS AS
(SELECT HOTEL, PRICE_RUPEES, NUMBER_OF_REVIEWS
 FROM DBO.HOTELS
 WHERE PRICE_RUPEES >= 15000)
SELECT *
FROM LUXURY_HOTELS
WHERE NUMBER_OF_REVIEWS >
(SELECT AVG(NUMBER_OF_REVIEWS) FROM DBO.HOTELS);