Categorize hotels as Budget, Mid Range, Premium, or Luxury based on price.

SELECT HOTEL, PRICE_RUPEES,
CASE
WHEN PRICE_RUPEES < 2500 THEN 'BUDGET'
WHEN PRICE_RUPEES < 7000 THEN 'MID RANGE'
WHEN PRICE_RUPEES < 15000 THEN 'PREMIUM'
ELSE 'LUXURY'
END AS HOTEL_CATEGORY
FROM DBO.HOTELS;

Count hotels in each price category.

SELECT
        CASE
        WHEN PRICE_RUPEES < 2500 THEN 'BUDGET'
        WHEN PRICE_RUPEES < 7000 THEN 'MID RANGE'
        WHEN PRICE_RUPEES < 15000 THEN 'PREMIUM'
        ELSE 'LUXURY'
        END AS HOTEL_CATEGORY,
    COUNT(*) AS TOTAL_HOTELS
FROM DBO.HOTELS
GROUP BY 
        CASE
        WHEN PRICE_RUPEES < 2500 THEN 'BUDGET'
        WHEN PRICE_RUPEES < 7000 THEN 'MID RANGE'
        WHEN PRICE_RUPEES < 15000 THEN 'PREMIUM'
        ELSE 'LUXURY'
        END;

Categorize hotels based on popularity using review counts.

SELECT HOTEL, NUMBER_OF_REVIEWS,
CASE
    WHEN NUMBER_OF_REVIEWS >= 3000 THEN 'HIGHLY POPULAR'
    WHEN NUMBER_OF_REVIEWS >= 1000 THEN 'POPULAR'
    ELSE 'LESS POPULAR'
END AS POPULARITY
FROM DBO.HOTELS;

Count hotels in each popularity segment.

SELECT
CASE
    WHEN NUMBER_OF_REVIEWS >= 3000 THEN 'HIGHLY POPULAR'
    WHEN NUMBER_OF_REVIEWS >= 1000 THEN 'POPULAR'
ELSE 'LESS POPULAR'
END AS POPULARITY, COUNT(*) AS TOTAL_HOTELS
FROM DBO.HOTELS
GROUP BY
CASE
    WHEN NUMBER_OF_REVIEWS >= 3000 THEN 'HIGHLY POPULAR'
    WHEN NUMBER_OF_REVIEWS >= 1000 THEN 'POPULAR'
ELSE 'LESS POPULAR'
END;

Label hotels as Expensive or Affordable.

SELECT HOTEL, PRICE_RUPEES,
CASE
    WHEN PRICE_RUPEES > 5000 THEN 'EXPENSIVE'
    ELSE 'AFFORDABLE'
END AS PRICE_LABEL
FROM DBO.HOTELS;

Count attractions by shift type.

SELECT
CASE
    WHEN IN_TIME2 = '-' THEN 'SINGLE SHIFT'
    ELSE 'MULTIPLE SHIFT'
END AS SHIFT_TYPE,
COUNT(*) AS TOTAL_ATTRACTIONS
FROM DBO.PLACES
GROUP BY
CASE
    WHEN IN_TIME2 = '-' THEN 'SINGLE SHIFT'
    ELSE 'MULTIPLE SHIFT'
END;

Count attractions by tourism type.

SELECT
CASE
    WHEN T.PRIORITY_1 = 'History and Culture' THEN 'Cultural Tourism'
    WHEN T.PRIORITY_1 = 'Museum' THEN 'Educational Tourism'
    WHEN T.PRIORITY_1 = 'Adventure' THEN 'Adventure Tourism'
    ELSE 'General Tourism'
END AS TOURISM_TYPE,
COUNT(*) AS TOTAL_ATTRACTIONS
FROM DBO.PLACES P
INNER JOIN DBO.TYPES T ON P.PID = T.PID
GROUP BY
CASE
    WHEN T.PRIORITY_1 = 'History and Culture' THEN 'Cultural Tourism'
    WHEN T.PRIORITY_1 = 'Museum' THEN 'Educational Tourism'
    WHEN T.PRIORITY_1 = 'Adventure' THEN 'Adventure Tourism'
ELSE 'General Tourism'
END
ORDER BY TOTAL_ATTRACTIONS DESC;

Identify attractions with single or multiple tourism categories.

SELECT P.POIs,
CASE
    WHEN T.PRIORITY_2 = '-' THEN 'SINGLE CATEGOY'     ---Since we have '-' in our data 
    ELSE 'MULTIPLE CATEGORIES'
END AS CATEGORY_TYPE
FROM DBO.PLACES P
INNER JOIN DBO.TYPES T ON P.PID = T.PID;
